config/routes.rb
Rails.application.routes.draw do

  # Routes for Room Reservation
  get 'room_reservation/index'
  get "room_reservation/search_allocations" => "room_reservation#search_allocations"
  get "room_reservation/schedule_time_cell/:week_day/:time" => "room_reservation#schedule_time_cell", as: :schedule_a_time
  get "room_reservation/:batch_id/teacher_allocations" => "room_reservation#teacher_allocations", as: :teacher_allocations
  post "scheduling_room" => "room_reservation#book_room", as: :scheduling_room
  delete "dismiss_reserved_room" => "room_reservation#dissmiss_reserved_room", as: :dismiss_room

  # Routes for Dashboard
  get "/load_reserved_details" => "dashboard#load_reserved_details", as: :load_details
  get ":username/time_table" => "dashboard#time_table", as: :time_table
  

  # Routes for Students and Teachers
  constraints(Subdomain) do
    resources :profiles, :path => ":username", only: [:index] do
      collection do
        get "/settings" => "profiles#edit", as: :edit
        put "settings/security" => "profiles#security", as: :security
        put "settings/profile" => "profiles#update", as: :profile
      end
    end

    %w(student teacher).each do |resource|
      resource_name = resource.pluralize
      devise_for resource_name.to_sym, :skip => [:passwords, :registrations], controllers: { confirmations: "resources/confirmations", sessions: "resources/sessions" }
      devise_scope resource.to_sym do
        get "#{resource_name}/login" => "resources/sessions#new", as: "#{resource_name}_login".to_sym
        get "#{resource_name}/login_after_confirmation" => "resources/sessions#login_after_confirmation", as: "#{resource_name}_login_after_confirmation".to_sym
      end

      authenticated resource.to_sym do
        root 'dashboard#index', as: "#{resource}_authenticated_root".to_sym
      end
    end
  end

  # Routes for Admin
  constraints :subdomain => "admin" do 
    devise_for :admins, :skip => [:passwords, :registrations, :confirmations], controllers: { sessions: "resources/sessions" }
    devise_scope :admin do
      get "admin/login" => "resources/sessions#new", as: :admins_login
    end

    %w(student teacher).each do |resource|
      devise_for resource.pluralize.to_sym, :skip => [:passwords, :confirmations, :sessions], controllers: { registrations: "resources/registrations" }
      devise_scope resource.to_sym do
        if resource == "student"
          get "#{resource.pluralize}/admissions/:batch_name" => "resources/registrations#new", as: "new_#{resource}".to_sym
        else
          get "#{resource.pluralize}/new" => "resources/registrations#new", as: "new_#{resource}".to_sym
        end
      end
    end
    
    scope :module => 'administrations' do
      # Admin Settings
      resources :settings, :path => "admin/settings", only: [:index] do 
        collection do
          get "/account" => "settings#admin_account", as: :admin_account
          put "/" => "settings#update", as: :update_account
          get "/week_days" => "settings#week_days_and_timings", as: :set_week_days
          get "/current_batches" => "settings#current_batches", as: :current_batches
        end
      end

      resources :admissions, only: [:index] do
        collection do 
          post "/cancel_admission" => "admissions#cancel_admission", as: :cancel
          post "/setup_admission" => "admissions#setup_admission", as: :setup
          get "/autocomplete_guardians_search" => "admissions#autocomplete_guardians_search", as: :autocomplete_guardians
          get "/get_parent/:parent_id" => "admissions#get_parent"
        end
      end

      # Admin Students
      resources :students, path: "students", only: [:index] do
        get "/search" => "students#search", on: :collection, as: :search
      end

      # Admin Teachers
      resources :teachers, path: "teachers", only: [:index, :update] do
        get "/search" => "teachers#search", on: :collection, as: :search
      end

      resources :time_table, path: "time_table", only: [:index] do
        get "/generate" => "time_table#show", as: :generate, on: :collection
      end
    end

    authenticated :admin do
      root 'dashboard#index', as: :admin_authenticated_root
    end
  end

  namespace :institutes do
    resources :batches, except: [:show, :edit, :new] do
      put "/add_sections" => "batches#add_sections", as: :add_sections
    end

    get "/get_sections" => "base#get_sections", as: :get_sections

    resources :classrooms, except: [:edit]
    resources :courses do 
      get "get_course/:semester_name" => "courses#get_course_by_section", on: :collection
    end
    resources :course_allocations, only: [:index, :create, :update] do
      collection do
        post "allocate"
        get ":batch_id/get_allocations" => "course_allocations#get_allocations", as: :get_allocations
        delete ":batch_id/remove_allocations" => "course_allocations#remove_allocations", as: :remove_allocations
        get ":batch_id/courses_and_sections"=> "course_allocations#courses_and_sections", as: :courses_and_sections
        delete ":teacher_id/remove_teacher_allocations"=> "course_allocations#remove_teacher_allocations", as: :remove_teacher_allocations
        get "/notify_teacher_for_approval" => "course_allocations#notify_teacher_for_approval", as: :notify_teacher
      end
    end
  end

  resources :dashboard, only: [:index]

  get "/about_us" => "landings#about"
  root to: "landings#home"
end

app/controllers/administrations/admin_service.rb
class Administrations::AdminService
  def call
    admin = Admin.find_or_create_by!(email: Rails.application.secrets.admin_email) do |admin|
      admin.password = Rails.application.secrets.admin_password
      admin.password_confirmation = Rails.application.secrets.admin_password
      admin.is_admin = true
      admin.username = Rails.application.secrets.admin_username
      # admin.confirm!
    end
  end

  def setting_admin_account
  	admin_user = call
  	@admin_account = admin_user.build_account
  	subdoamin_name = admin_user.email.split("@").first
  	@admin_account.subdomain = subdoamin_name
  	@admin_account.save
  end

  # module_function :call, :setting_admin_account
end

app/controllers/administrations/admissions_controller.rb
module Administrations
	class AdmissionsController < ApplicationController
		before_action :get_new_admission_sections, only: [:new, :create]

		def setup_admission
	  	admission_params_hash = {
				:section => params[:section],
				:batch => params[:batch],
	      :semester => params[:semester]
	  	}
 	
	  	@admission = Student.build_admission(admission_params_hash)

	  	@batch_name = Batch.find(@admission.batch_id).batch_name if params[:batch].present?

	    respond_to do |format|
	    	if @admission.valid? == true
	        session[:admission] = @admission
	    		format.json { render :json => { status: :ok, redirect_url: new_student_path(@batch_name) }, status: :created }
	  		else
					format.json { render :json => { status: :error, errors: @admission.errors.full_messages.map { |msg| content_tag(:li, msg) }.join }, status: :created }
	  		end
	    end
	  end

		def cancel_admission
			session[:admission] = nil
			redirect_to students_path
			flash[:notice] = "Admission Cancelled"
		end

		def autocomplete_guardians_search
			@guardian_names = Parent.all.collect do |parent|  {
	        :id => parent.id,
	        :name => parent.name
	      }
	    end.to_json

			respond_to do |format|
				format.json { render :json => @guardian_names }
			end
		end

		def get_parent
			@parent = Parent.find(params[:parent_id]) if params[:parent_id]
			respond_to do |format|
				format.js
			end
		end

		private

		def get_new_admission_sections
			@admission_sections = Batch.find(session[:admission]["batch_id"]).sections
		end
	end
end

app/controllers/administrations/settings_controller.rb
module Administrations
	class	SettingsController < ApplicationController
		before_action :authenticate_admin!
		before_action -> { sidebar(true) }
		before_action -> { admin_settings_aside(true) }

		def admin_account
			@admin = current_admin
		end

		def week_days_and_timings
			@week_days = TimeSlot.week_days
			@normal_timings = TimeSlot.non_fridays
			@friday_timings = TimeSlot.fridays
		end

		def current_batches
			@current_batches = Batch.current_batches
		end

		def update
			@admin = current_admin
			if @admin.update_attributes(admin_params)
				sign_in :admin, @admin, :bypass => true
				redirect_to admin_account_settings_path, notice: "Account Updated"
			else
				render :admin_account
			end
		end

		private

		def admin_params
			params.require(:admin).permit(:email, :username, :password, :password_confirmation)
		end
	end
end

app/controllers/administrations/students_controller.rb
module Administrations
	class StudentsController < ApplicationController
		respond_to :js, :html
		add_breadcrumb "Students"
		
		def index
			@sections = Section.where(batch_id: Batch.current_batches.first["id"])
			@batches = Batch.current_batches

			respond_with :js, :html
		end


		def search
			@students, @batch = Search.students_search(params)
			respond_with :js
		end
	end
end

app/controllers/administrations/teachers_controller.rb
module Administrations
	class	TeachersController < ApplicationController
		add_breadcrumb "Teachers"
		
		def index
			@teachers = Teacher.present
		end

		def search
			@teachers = Search.teachers_search(params)
			render :index
		end

		def update
			@teacher = Teacher.find(params[:id])
			respond_to do |format|
				if @teacher.update_attributes(teacher_params)
					format.json { respond_with_bip(@teacher) }
				else
					format.json { respond_with_bip(@teacher) }
				end
			end
		end

		def teacher_params
			params.require(:teacher).permit(:full_name, :date_of_birth, :joining_date, :phone)
		end
	end
end

app/controllers/administrations/time_table_controller.rb
class Administrations::TimeTableController < ApplicationController
  include TimeTableSlots

  prepend_before_action :slots_data, only: [:show]
  add_breadcrumb "Time Table"

  def index
    @batches = Batch.current_batches
    @sections = @batches.first["sections"]
  end

  def show
    @reservations = TimeTable.generate(params)
    @params = params
    respond_to do |format|
      unless @reservations.blank?
        format.js {}
        format.html { render partial: 'administrations/time_table/generated_time_table' }
      else
        format.json { render json: { status: :empty, alert: TimeTable::NULL_RESERVATIONS } }
      end
    end
  end
end

app/controllers/admins/students_controller.rb
module Admins
	class StudentsController < ApplicationController
		respond_to :js, :html
		
		def index
			@sections = Batch.first.sections

			@batches = Batch.current_batches

			respond_with :js, :html
		end

		def search
			@sections = Section.all
			@batches = Batch.all
			@students, @batch = Student.search(params)
			respond_with :js
		end
	end
end

app/controllers/students/registrations_controller.rb
module Students
	class RegistrationsController < Devise::RegistrationsController
		before_action :get_new_admission_sections, only: [:new, :create]

		def setup_admission
	  	admission_params_hash = {
				:section => params[:section],
				:batch => params[:batch],
	      :semester => params[:semester]
	  	}

	  	
	  	@admission = Student.build_admission(admission_params_hash)
	  	@admission.check_valididty = false

	  	@batch_name = Batch.find(@admission.batch_id).name.split("-").first if params[:batch].present?

	    respond_to do |format|
	    	if @admission.valid? == true
	        session[:admission] = @admission
	    		format.json { render :json => { status: :ok, redirect_url: new_admissions_path(@batch_name) }, status: :created }
	  		else
					format.json { render :json => { status: :error, errors: @admission.errors.full_messages.map { |msg| content_tag(:li, msg) }.join }, status: :created }
	  		end
	    end
	  end

		def new
			@new_admission = Student.enroll_new(session[:admission])
		end

		def create
			@new_admission = Student.enroll_new(admissions_params)
			@new_admission.check_valididty = false
			respond_to do |format|
				if @new_admission.save
					format.html { redirect_to students_path, notice: "#{@new_admission.full_name} has been enrolled successfully." }
					format.json { render :json => @new_admission }
				else
					format.html { render :new }
					format.json { render :json => @new_admission.errors.full_messages }
					flash[:alert] = "Please Review the Errors Below"
				end
			end
		end

		def cancel_admission
			session[:admission] = nil
			redirect_to students_path
			flash[:notice] = "Admission Cancelled"
		end

		def autocomplete_guardians_search
			@guardian_names = Parent.all.collect do |parent|  {
	        :id => parent.id,
	        :name => parent.name
	      }
	    end.to_json

			respond_to do |format|
				format.json { render :json => @guardian_names }
			end
		end

		def get_parent
			@parent = Parent.find(params[:parent_id]) if params[:parent_id]
			respond_to do |format|
				format.js
			end
		end

		private

		def admissions_params
			devise_parameter_sanitizer.sanitize(:student)
		end

		def get_new_admission_sections
			@admission_sections = Batch.find(session[:admission]["batch_id"]).sections
		end
	end
end

app/helpers/administrations/time_table_helper.rb
module Administrations::TimeTableHelper
  include RoomReservationHelper

  def rendering_time_table(params = {})
    render :layout => 'layouts/shared/time_table' do |time_table|
      html = ""
      if time_table.time_slot.booked_room_detail(params).each do |allocation|
        html << marked_cell(allocation, false, true)
      end.empty?
        html << "---"
      end
      html.html_safe
    end
  end

  def profile_time_popover_title(slot)
    return "Classes on #{slot.week_day}, #{slot.timings}"
  end

  def profile_time_popover_content(teacher, slot)
    render :partial => 'layouts/shared/teacher_dashboard_slot_detail', locals: { teacher: teacher, slot: slot }  
  end
end

app/helpers/students_helper.rb
module StudentsHelper
	def students_sections_list(sections)
		@sections = sections
		select_tag :student_section, options_for_select(@sections.map{|section| [section.name, section.id]}), class: "form-control", prompt: "Select Section"
	end
end

app/views/administrations/students/_students_list.html.erb
<% if students.present? %>
	<div class="table-responsive">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Roll #</th>
					<th>Name</th>
					<th>Joining Date</th>
					<th>Passed Out</th>
					<th>Semester</th>
					<th>Section</th>
					<th>Gender</th>
				</tr>
			</thead>
			<tbody>
				<% students.each do |student| %>
					<tr>
						<td><%= student.roll_number %></td>
						<td><%= student.full_name %></td>
						<td><%= student.joining_date %></td>
						<td><%= student.passed_out %></td>
						<td><%= student.semester.try(:name) %></td>
						<td><%= student.section.try(:name) %></td>
						<td><%= student.gender %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
<% else %>
	<br />
	<div class="alert alert-info">
		<blockquote>
			No Students availble in <strong><%= batch_name %></strong>
		</blockquote>
	</div>
<% end %>

app/views/administrations/students/index.html.erb
<div class="page-header">
	<h2>
		Students <small>Enrolled</small>
    <a href="#" class="pull-right btn btn-info" data-target="#admission_modal" data-toggle="modal"><i class="fa fa-graduation-cap"></i> New Student</a>
	</h2>
</div>
<%= form_tag search_students_path(format: :js), remote: true, method: :get, id: "search_students_form" do %>
	<%= hidden_field_tag :batch_id_param %>
	<div class="row">
		<div class="col-md-12">
			<div class="row">
				<div class="col-md-3">
					<label>Roll No:</label>
					<%= text_field_tag :roll_no, params[:roll_no], class: "form-control", placeholder: "Enter Roll Number" %>
				</div>
				<div class="col-md-3">
					<label>Name:</label>
					<%= text_field_tag :student_name, params[:student_name], class: "form-control", placeholder: "Enter Name" %>
				</div>
				<div class="col-md-3">
					<label>Section:</label>
					<div id="students_sections">
						<%= students_sections_list(@sections) %>
					</div>
				</div>
			</div>
		</div>
	</div>
	<br />
	<div class="row">
		<div class="col-md-6">
			<%= submit_tag "Search", class: "btn btn-danger" %>
			<%= link_to "Clear", students_path, class: "btn btn-default" %>
		</div>
	</div>
<% end %>
<br />
<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
	  <ul class="nav nav-tabs students_search_index" role="tablist">
	  	<% @batches.each_with_index do |batch, count| %>
	  		<% count += 1 %>
	    	<li role="presentation" class="student_batch_name_count_<%= batch['id'] %>">
	    		<%= link_to search_students_path(batch_id_param: batch['id'], format: :js), remote: true, "data-target" => "##{batch['name']}_#{count}", "data-toggle" => "tab", onclick: "getBatchid(this, #{batch['id']});", id: "tab_student_#{batch['id']}" do %>
	    			<%= "#{batch['name']} (#{batch['students']})" %>
	    		<% end %>
    		</li>
    	<% end %>
	  </ul>

	  <div class="tab-content students_search_index">
	  	<% @batches.each_with_index do |batch, count| %>
	  		<% count += 1 %>
		    <div role="tabpanel" class="tab-pane fade in" data-batch-id="<%= batch['id'] %>" id="<%= batch['name'] %>_<%= count %>">
		    	<div id="students_in_<%= batch['id'] %>">
		    		<% if batch['id'] == @batches.first['id'] %>
		    			<%= render "students_list", students: Student.where(batch_id: batch["id"]), batch_name: batch['name'] %>
	    			<% end %>
	    		</div>
		    </div>
	    <% end %>
	  </div>
	</div>
</div>

<%= render partial: "administrations/admissions/enroll_form" %>

app/views/administrations/students/search.js.erb
$("a#tab_student_<%= @batch.id %>").bind("ajax:beforeSend", function(evt, data, status, xhr){
	// $("#students_in_<%= @batch.id %>").html("<br /><div class='alert alert-danger'><blockquote><i class='fa fa-spinner fa-spin fa-2x'></i> <span class='font-size:32px;'>Loading</span></blockquote></div>");
}).bind("ajax:success", function(evt, data, status, xhr){
	$("#students_sections").html("<%= escape_javascript(students_sections_list(@batch.sections)).html_safe %>")

	setTimeout(function() {
	  $('div.students_search_index').find("div.tab-pane").each(function() {
	  	if (!$(this).hasClass("active")) {
		    $(this).find("div").empty();
		  }
	  });
	}, 500);

	$("ul.students_search_index").find("li").each(function(){
		if ($(this).hasClass("active")) {
		  $(this).css("font-weight", "bold");
		  $(this).find("a").css("border-left", "4px solid #CF9451")
		} else {
		  $(this).css("font-weight", "normal");
		  $(this).find("a").css("border-left", "0px")
		}
	})

	$(".student_batch_name_count_<%= @batch.id %> a").html("<%= @batch.batch_name %> (<%= @batch.students.select('id').count %>)")
	$("#students_in_<%= @batch.id %>").hide().html("<%= escape_javascript(render 'students_list', students: @students, batch_name: @batch.batch_name).html_safe %>").fadeIn(300);	

}).bind("ajax:error", function(evt, data, status, xhr){
	swal("Oops Something went wrong!")
});

$("form#search_students_form").on("ajax:success", function(evt, data, status, xhr){
	$("#students_in_<%= @batch.id %>").hide().html("<%= escape_javascript(render 'students_list', students: @students, batch_name: @batch.batch_name).html_safe %>").fadeIn(100);	
}).on("ajax:error", function(evt, data, status, xhr){
	swal("Oops Something went wrong!")
});