config/routes.rb
Rails.application.routes.draw do

  # Routes for Room Reservation
  get 'room_reservation/index'
  get "room_reservation/search_allocations" => "room_reservation#search_allocations"
  get "room_reservation/schedule_time_cell/:week_day/:time" => "room_reservation#schedule_time_cell", as: :schedule_a_time
  get "room_reservation/:batch_id/teacher_allocations" => "room_reservation#teacher_allocations", as: :teacher_allocations
  post "scheduling_room" => "room_reservation#book_room", as: :scheduling_room
  delete "dismiss_reserved_room" => "room_reservation#dissmiss_reserved_room", as: :dismiss_room

  # Routes for Dashboard
  get "/load_reserved_details" => "dashboard#load_reserved_details", as: :load_details
  get ":username/time_table" => "dashboard#time_table", as: :time_table
  

  # Routes for Students and Teachers
  constraints(Subdomain) do
    resources :profiles, :path => ":username", only: [:index] do
      collection do
        get "/settings" => "profiles#edit", as: :edit
        put "settings/security" => "profiles#security", as: :security
        put "settings/profile" => "profiles#update", as: :profile
      end
    end

    %w(student teacher).each do |resource|
      resource_name = resource.pluralize
      devise_for resource_name.to_sym, :skip => [:passwords, :registrations], controllers: { confirmations: "resources/confirmations", sessions: "resources/sessions" }
      devise_scope resource.to_sym do
        get "#{resource_name}/login" => "resources/sessions#new", as: "#{resource_name}_login".to_sym
        get "#{resource_name}/login_after_confirmation" => "resources/sessions#login_after_confirmation", as: "#{resource_name}_login_after_confirmation".to_sym
      end

      authenticated resource.to_sym do
        root 'dashboard#index', as: "#{resource}_authenticated_root".to_sym
      end
    end
  end

  # Routes for Admin
  constraints :subdomain => "admin" do 
    devise_for :admins, :skip => [:passwords, :registrations, :confirmations], controllers: { sessions: "resources/sessions" }
    devise_scope :admin do
      get "admin/login" => "resources/sessions#new", as: :admins_login
    end

    %w(student teacher).each do |resource|
      devise_for resource.pluralize.to_sym, :skip => [:passwords, :confirmations, :sessions], controllers: { registrations: "resources/registrations" }
      devise_scope resource.to_sym do
        if resource == "student"
          get "#{resource.pluralize}/admissions/:batch_name" => "resources/registrations#new", as: "new_#{resource}".to_sym
        else
          get "#{resource.pluralize}/new" => "resources/registrations#new", as: "new_#{resource}".to_sym
        end
      end
    end
    
    scope :module => 'administrations' do
      # Admin Settings
      resources :settings, :path => "admin/settings", only: [:index] do 
        collection do
          get "/account" => "settings#admin_account", as: :admin_account
          put "/" => "settings#update", as: :update_account
          get "/week_days" => "settings#week_days_and_timings", as: :set_week_days
          get "/current_batches" => "settings#current_batches", as: :current_batches
        end
      end

      resources :admissions, only: [:index] do
        collection do 
          post "/cancel_admission" => "admissions#cancel_admission", as: :cancel
          post "/setup_admission" => "admissions#setup_admission", as: :setup
          get "/autocomplete_guardians_search" => "admissions#autocomplete_guardians_search", as: :autocomplete_guardians
          get "/get_parent/:parent_id" => "admissions#get_parent"
        end
      end

      # Admin Students
      resources :students, path: "students", only: [:index] do
        get "/search" => "students#search", on: :collection, as: :search
      end

      # Admin Teachers
      resources :teachers, path: "teachers", only: [:index, :update] do
        get "/search" => "teachers#search", on: :collection, as: :search
      end

      resources :time_table, path: "time_table", only: [:index] do
        get "/generate" => "time_table#show", as: :generate, on: :collection
      end
    end

    authenticated :admin do
      root 'dashboard#index', as: :admin_authenticated_root
    end
  end

  namespace :institutes do
    resources :batches, except: [:show, :edit, :new] do
      put "/add_sections" => "batches#add_sections", as: :add_sections
    end

    get "/get_sections" => "base#get_sections", as: :get_sections

    resources :classrooms, except: [:edit]
    resources :courses do 
      get "get_course/:semester_name" => "courses#get_course_by_section", on: :collection
    end
    resources :course_allocations, only: [:index, :create, :update] do
      collection do
        post "allocate"
        get ":batch_id/get_allocations" => "course_allocations#get_allocations", as: :get_allocations
        delete ":batch_id/remove_allocations" => "course_allocations#remove_allocations", as: :remove_allocations
        get ":batch_id/courses_and_sections"=> "course_allocations#courses_and_sections", as: :courses_and_sections
        delete ":teacher_id/remove_teacher_allocations"=> "course_allocations#remove_teacher_allocations", as: :remove_teacher_allocations
        get "/notify_teacher_for_approval" => "course_allocations#notify_teacher_for_approval", as: :notify_teacher
      end
    end
  end

  resources :dashboard, only: [:index]

  get "/about_us" => "landings#about"
  root to: "landings#home"
end

app/views/layouts/shared/_admin_top_bar_links.html.erb
<ul class="nav navbar-nav">
  <li>
    <%= link_to students_path do %>
      <i class="fa fa-graduation-cap"></i> Enrollments
    <% end %>
  </li>
  <li>
    <%= link_to teachers_path do %>
        <i class="fa fa-users"></i> Teachers
    <% end %>
  </li>
  <li>
    <%= link_to time_table_index_path do %>
        <i class="glyphicon glyphicon-calendar"></i> Generate Time Table
    <% end %>
  </li>
</ul>

<ul class="nav navbar-nav navbar-top-links navbar-right">
  <li>
    <%= link_to institutes_batches_path do%>
      <i class="fa fa-university"></i> Institute
    <% end %>
  </li>
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
    </a>
    <ul class="dropdown-menu dropdown-animated dropdown-user">
        <li>
          <%= link_to admin_account_settings_path do %>
            <i class="fa fa-user fa-fw"></i> Settings
          <% end %>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to destroy_admin_session_path, method: "delete" do %>
            <i class="fa fa-sign-out fa-fw"></i> Logout
          <% end %>
        </li>
    </ul>
  </li>
</ul>

app/views/layouts/shared/_aside.erb
<% if @admin_institute_settings_aside %>
  <div class="container-fluid">
    <div class="page-heading-admin-settings">
      Institute Settings
    </div>
    <div class="row">
      <div class="col-md-3">
        <div class="settings-list-group">
          <%= link_to "Batches", institutes_batches_path, class: "list-group-item" %>
          <%= link_to "Classrooms", institutes_classrooms_path, class: "list-group-item" %>
          <%= link_to "Courses", institutes_courses_path, class: "list-group-item" %>
          <%= link_to "Course Allocations", institutes_course_allocations_path, class: "list-group-item" %>
        </div>
      </div>
      <div class="col-md-9">
        <%= yield :institute_settings %>
      </div>
    </div>
  </div>
<% end %>

<% if @admin_settings_aside %>
  <div class="container-fluid">
    <div class="page-heading-admin-settings">
      Settings
    </div>
    <div class="row">
      <div class="col-md-3">
        <div class="admin-settings settings-list-group">
          <%= link_to "Admin Account", admin_account_settings_path, class: "list-group-item" %>
          <%= link_to "Week Days & Timings", set_week_days_settings_path, class: "list-group-item" %>
          <%= link_to "Batches", current_batches_settings_path, class: "list-group-item" %>
        </div>
      </div>
      <div class="col-md-9">
        <%= yield :admin_settings %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/shared/_breadcrumbs.html.erb
<% if resource_signed_in? %>
	<ol class="breadcrumb">
		<i class="glyphicon glyphicon-dashboard"></i>
		<%= render_breadcrumbs :tag => :li, :separator => "" %>
	</ol>
<% end %>

app/views/layouts/shared/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <hr/>
      <div class="col-md-7">
        <a href="#">Terms of Service</a>
        <a href="#">Privacy</a>
        <a href="#">Security</a>
      </div>
      <div class="col-md-5">
        <p class="muted pull-right">© 2015 Dot Mark. All rights reserved</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/shared/_head.html.erb
<title><%= "Dotmark - " + title %></title>
<% cache "head_cache_v=1" do %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Dotmark" %>">
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet" />
	<script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>
<% end %>
<%= csrf_meta_tags %>

<%= javascript_tag do %>
	window.current_resource_account = "N/A"

	<% if @account["resource_type"] == "Teacher" %>
  	window.current_resource_account = "<%= @account["subdomain"] %>"
  	window.signed_in_teacher = "<%= @account["resource"]["id"] %>"
	<% end %>
<% end %>

app/views/layouts/shared/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<script type="text/javascript">
	$(document).ready(function(){
		<% flash.each do |name, msg| %>
  		<% if msg.is_a?(String) %>
  			$.notify({
					// options
					icon: "glyphicon <%= name.to_s == 'notice' ? 'glyphicon-ok' : 'glyphicon-warning-sign'%>",
					title: "<strong><%= name.to_s == 'notice' ? 'Success' : 'Error'%>: </strong>",	
					message: '<%= msg.html_safe %>'
				},{
					element: 'body',
					position: null,
					type: "<%= name.to_s == 'notice' ? 'success' : name.to_s == 'warning' ? 'warning' : 'danger' %>",
					allow_dismiss: true,
					newest_on_top: false,
					showProgressbar: false,
					offset: {
						y: 50,
						x: 33
					},
					placement: {
						from: "top",
						align: "right"
					}
				});
  		<% end %>
		<% end %>
	});
</script>

app/views/layouts/shared/_navigation.html.erb
<% if resource_signed_in? %>
  <div class="container">
    <nav class="navbar navbar-inverse admin-navbar">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display
        -->
        <div class="navbar-header">
          <button aria-expanded="false" class="navbar-toggle collapsed" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
            <!-- Dot Mark -->
            <i class="fa fa-tachometer fa-2x"></i>
          </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling
        -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <%= render partial: "layouts/shared/#{current_resource_name}_top_bar_links" %>
        </div>
      </div>
    </nav>
  </div>
<% end %>

app/views/layouts/shared/_student_top_bar_links.html.erb
<ul class="nav navbar-nav navbar-top-links navbar-right">
  <li class="navbar-image">
    <img src="<%= image_path(navbar_image(current_resource)) %>", class="img-rounded img-responsive">
  </li>
  <li>
    <%= link_to profiles_url(subdomain: @account["subdomain"], username: current_resource.username) do %>
      <i class="fa fa-user fa-fw"></i> My Profile
    <% end %>
  </li>
  <li>
    <%= link_to destroy_student_session_path, method: "delete" do %>
      <i class="fa fa-sign-out fa-fw"></i> Logout
    <% end %>
  </li>
</ul>

app/views/layouts/shared/_teacher_dashboard_slot_detail.html.erb
<table class='table table-striped teacher_slot_detail_dashboard'>
  <tr>
    <th>#</th>
    <th>Room</th>
    <th>Sec</th>
    <th>Batch</th>
    <th>Course</th>
  </tr>
  <% teacher.teacher_time_slots(slot).each_with_index do |reservation, count| %>
    <% count += 1 %>
    <tr>
      <td><%=count %></td>
      <td><%=reservation.classroom.name %></td>
      <td><%=reservation.course_allocation.section.name %></td>
      <td><%=reservation.course_allocation.batch.batch_name %></td>
      <td><%=reservation.course_allocation.course.detailed_name %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/shared/_teacher_top_bar_links.html.erb
<ul class="nav navbar-nav navbar-top-links navbar-right">
  <li class="navbar-image">
    <img src="<%= image_path(navbar_image(current_resource)) %>", class="img-rounded img-responsive">
  </li>
  <li>
    <%= link_to profiles_url(subdomain: @account["subdomain"], username: current_resource.username) do %>
      <i class="fa fa-user fa-fw"></i> My Profile
    <% end %>
  </li>
  <li>
    <%= link_to destroy_teacher_session_path, method: "delete" do %>
      <i class="fa fa-sign-out fa-fw"></i> Logout
    <% end %>
  </li>
</ul>

app/views/layouts/shared/_time_table.html.erb
<div class="row">
  <div class="col-md-12">
    <table class="table table-bordered" id="time_table">
      <tr>
        <td align="center" rowspan="2">
          <strong>Fridays</strong>
          <div class="divider-cell"></div>
          <strong>Days</strong>
        </td>
        <% @fridays.each do |timing| %>
            <td align="center"><%= timing.timings %></td>
        <% end %>
      </tr>
      <tr>
        <% @non_fridays.each do |timing| %>
            <td align="center"><%= timing.timings %></td>
        <% end %>
      </tr>
      <tr class="period_days">
        <td align="center"><strong>Week Days</strong></td>
        <% (1..9).each do |period_days| %>
            <td align="center"><%= period_days %></td>
        <% end %>
      </tr>
      <% @week_days.each_with_index do |days, i| %>
          <tr>
            <td align="center"><strong><%= days.week_day %></strong></td>
            <% TimeSlot.for(days.week_day).each do |time_slot| %>
                <td align="center" class="loader-cell-<%= time_slot.id %>" data-time-slot-id="<%= time_slot.id %>">
                  <%= yield(Struct.new(:time_slot).new(time_slot)) %>
                </td>
            <% end %>
          </tr>
      <% end %>
    </table>
  </div>
</div>