config/routes.rb
Rails.application.routes.draw do

  # Routes for Room Reservation
  get 'room_reservation/index'
  get "room_reservation/search_allocations" => "room_reservation#search_allocations"
  get "room_reservation/schedule_time_cell/:week_day/:time" => "room_reservation#schedule_time_cell", as: :schedule_a_time
  get "room_reservation/:batch_id/teacher_allocations" => "room_reservation#teacher_allocations", as: :teacher_allocations
  post "scheduling_room" => "room_reservation#book_room", as: :scheduling_room
  delete "dismiss_reserved_room" => "room_reservation#dissmiss_reserved_room", as: :dismiss_room

  # Routes for Dashboard
  get "/load_reserved_details" => "dashboard#load_reserved_details", as: :load_details
  get ":username/time_table" => "dashboard#time_table", as: :time_table
  

  # Routes for Students and Teachers
  constraints(Subdomain) do
    resources :profiles, :path => ":username", only: [:index] do
      collection do
        get "/settings" => "profiles#edit", as: :edit
        put "settings/security" => "profiles#security", as: :security
        put "settings/profile" => "profiles#update", as: :profile
      end
    end

    %w(student teacher).each do |resource|
      resource_name = resource.pluralize
      devise_for resource_name.to_sym, :skip => [:passwords, :registrations], controllers: { confirmations: "resources/confirmations", sessions: "resources/sessions" }
      devise_scope resource.to_sym do
        get "#{resource_name}/login" => "resources/sessions#new", as: "#{resource_name}_login".to_sym
        get "#{resource_name}/login_after_confirmation" => "resources/sessions#login_after_confirmation", as: "#{resource_name}_login_after_confirmation".to_sym
      end

      authenticated resource.to_sym do
        root 'dashboard#index', as: "#{resource}_authenticated_root".to_sym
      end
    end
  end

  # Routes for Admin
  constraints :subdomain => "admin" do 
    devise_for :admins, :skip => [:passwords, :registrations, :confirmations], controllers: { sessions: "resources/sessions" }
    devise_scope :admin do
      get "admin/login" => "resources/sessions#new", as: :admins_login
    end

    %w(student teacher).each do |resource|
      devise_for resource.pluralize.to_sym, :skip => [:passwords, :confirmations, :sessions], controllers: { registrations: "resources/registrations" }
      devise_scope resource.to_sym do
        if resource == "student"
          get "#{resource.pluralize}/admissions/:batch_name" => "resources/registrations#new", as: "new_#{resource}".to_sym
        else
          get "#{resource.pluralize}/new" => "resources/registrations#new", as: "new_#{resource}".to_sym
        end
      end
    end
    
    scope :module => 'administrations' do
      # Admin Settings
      resources :settings, :path => "admin/settings", only: [:index] do 
        collection do
          get "/account" => "settings#admin_account", as: :admin_account
          put "/" => "settings#update", as: :update_account
          get "/week_days" => "settings#week_days_and_timings", as: :set_week_days
          get "/current_batches" => "settings#current_batches", as: :current_batches
        end
      end

      resources :admissions, only: [:index] do
        collection do 
          post "/cancel_admission" => "admissions#cancel_admission", as: :cancel
          post "/setup_admission" => "admissions#setup_admission", as: :setup
          get "/autocomplete_guardians_search" => "admissions#autocomplete_guardians_search", as: :autocomplete_guardians
          get "/get_parent/:parent_id" => "admissions#get_parent"
        end
      end

      # Admin Students
      resources :students, path: "students", only: [:index] do
        get "/search" => "students#search", on: :collection, as: :search
      end

      # Admin Teachers
      resources :teachers, path: "teachers", only: [:index, :update] do
        get "/search" => "teachers#search", on: :collection, as: :search
      end

      resources :time_table, path: "time_table", only: [:index] do
        get "/generate" => "time_table#show", as: :generate, on: :collection
      end
    end

    authenticated :admin do
      root 'dashboard#index', as: :admin_authenticated_root
    end
  end

  namespace :institutes do
    resources :batches, except: [:show, :edit, :new] do
      put "/add_sections" => "batches#add_sections", as: :add_sections
    end

    get "/get_sections" => "base#get_sections", as: :get_sections

    resources :classrooms, except: [:edit]
    resources :courses do 
      get "get_course/:semester_name" => "courses#get_course_by_section", on: :collection
    end
    resources :course_allocations, only: [:index, :create, :update] do
      collection do
        post "allocate"
        get ":batch_id/get_allocations" => "course_allocations#get_allocations", as: :get_allocations
        delete ":batch_id/remove_allocations" => "course_allocations#remove_allocations", as: :remove_allocations
        get ":batch_id/courses_and_sections"=> "course_allocations#courses_and_sections", as: :courses_and_sections
        delete ":teacher_id/remove_teacher_allocations"=> "course_allocations#remove_teacher_allocations", as: :remove_teacher_allocations
        get "/notify_teacher_for_approval" => "course_allocations#notify_teacher_for_approval", as: :notify_teacher
      end
    end
  end

  resources :dashboard, only: [:index]

  get "/about_us" => "landings#about"
  root to: "landings#home"
end

app/controllers/administrations/admin_service.rb
class Administrations::AdminService
  def call
    admin = Admin.find_or_create_by!(email: Rails.application.secrets.admin_email) do |admin|
      admin.password = Rails.application.secrets.admin_password
      admin.password_confirmation = Rails.application.secrets.admin_password
      admin.is_admin = true
      admin.username = Rails.application.secrets.admin_username
      # admin.confirm!
    end
  end

  def setting_admin_account
  	admin_user = call
  	@admin_account = admin_user.build_account
  	subdoamin_name = admin_user.email.split("@").first
  	@admin_account.subdomain = subdoamin_name
  	@admin_account.save
  end

  # module_function :call, :setting_admin_account
end

app/controllers/administrations/admissions_controller.rb
module Administrations
	class AdmissionsController < ApplicationController
		before_action :get_new_admission_sections, only: [:new, :create]

		def setup_admission
	  	admission_params_hash = {
				:section => params[:section],
				:batch => params[:batch],
	      :semester => params[:semester]
	  	}
 	
	  	@admission = Student.build_admission(admission_params_hash)

	  	@batch_name = Batch.find(@admission.batch_id).batch_name if params[:batch].present?

	    respond_to do |format|
	    	if @admission.valid? == true
	        session[:admission] = @admission
	    		format.json { render :json => { status: :ok, redirect_url: new_student_path(@batch_name) }, status: :created }
	  		else
					format.json { render :json => { status: :error, errors: @admission.errors.full_messages.map { |msg| content_tag(:li, msg) }.join }, status: :created }
	  		end
	    end
	  end

		def cancel_admission
			session[:admission] = nil
			redirect_to students_path
			flash[:notice] = "Admission Cancelled"
		end

		def autocomplete_guardians_search
			@guardian_names = Parent.all.collect do |parent|  {
	        :id => parent.id,
	        :name => parent.name
	      }
	    end.to_json

			respond_to do |format|
				format.json { render :json => @guardian_names }
			end
		end

		def get_parent
			@parent = Parent.find(params[:parent_id]) if params[:parent_id]
			respond_to do |format|
				format.js
			end
		end

		private

		def get_new_admission_sections
			@admission_sections = Batch.find(session[:admission]["batch_id"]).sections
		end
	end
end

app/controllers/administrations/settings_controller.rb
module Administrations
	class	SettingsController < ApplicationController
		before_action :authenticate_admin!
		before_action -> { sidebar(true) }
		before_action -> { admin_settings_aside(true) }

		def admin_account
			@admin = current_admin
		end

		def week_days_and_timings
			@week_days = TimeSlot.week_days
			@normal_timings = TimeSlot.non_fridays
			@friday_timings = TimeSlot.fridays
		end

		def current_batches
			@current_batches = Batch.current_batches
		end

		def update
			@admin = current_admin
			if @admin.update_attributes(admin_params)
				sign_in :admin, @admin, :bypass => true
				redirect_to admin_account_settings_path, notice: "Account Updated"
			else
				render :admin_account
			end
		end

		private

		def admin_params
			params.require(:admin).permit(:email, :username, :password, :password_confirmation)
		end
	end
end

app/controllers/administrations/students_controller.rb
module Administrations
	class StudentsController < ApplicationController
		respond_to :js, :html
		add_breadcrumb "Students"
		
		def index
			@sections = Section.where(batch_id: Batch.current_batches.first["id"])
			@batches = Batch.current_batches

			respond_with :js, :html
		end


		def search
			@students, @batch = Search.students_search(params)
			respond_with :js
		end
	end
end

app/controllers/administrations/teachers_controller.rb
module Administrations
	class	TeachersController < ApplicationController
		add_breadcrumb "Teachers"
		
		def index
			@teachers = Teacher.present
		end

		def search
			@teachers = Search.teachers_search(params)
			render :index
		end

		def update
			@teacher = Teacher.find(params[:id])
			respond_to do |format|
				if @teacher.update_attributes(teacher_params)
					format.json { respond_with_bip(@teacher) }
				else
					format.json { respond_with_bip(@teacher) }
				end
			end
		end

		def teacher_params
			params.require(:teacher).permit(:full_name, :date_of_birth, :joining_date, :phone)
		end
	end
end

app/controllers/administrations/time_table_controller.rb
class Administrations::TimeTableController < ApplicationController
  include TimeTableSlots

  prepend_before_action :slots_data, only: [:show]
  add_breadcrumb "Time Table"

  def index
    @batches = Batch.current_batches
    @sections = @batches.first["sections"]
  end

  def show
    @reservations = TimeTable.generate(params)
    @params = params
    respond_to do |format|
      unless @reservations.blank?
        format.js {}
        format.html { render partial: 'administrations/time_table/generated_time_table' }
      else
        format.json { render json: { status: :empty, alert: TimeTable::NULL_RESERVATIONS } }
      end
    end
  end
end

app/helpers/administrations/time_table_helper.rb
module Administrations::TimeTableHelper
  include RoomReservationHelper

  def rendering_time_table(params = {})
    render :layout => 'layouts/shared/time_table' do |time_table|
      html = ""
      if time_table.time_slot.booked_room_detail(params).each do |allocation|
        html << marked_cell(allocation, false, true)
      end.empty?
        html << "---"
      end
      html.html_safe
    end
  end

  def profile_time_popover_title(slot)
    return "Classes on #{slot.week_day}, #{slot.timings}"
  end

  def profile_time_popover_content(teacher, slot)
    render :partial => 'layouts/shared/teacher_dashboard_slot_detail', locals: { teacher: teacher, slot: slot }  
  end
end

app/views/administrations/admissions/_batches_sections.html.erb
<% if sections.present? %>
	<ul class="list-inline">
		
		<% sections.each do |section| %>
			<li>
				<div class="radio" style="margin-top:1px;">
					<% if defined?(new_admission) and new_admission %>
						<!-- After Initialization -->
						<%= radio_button_tag "student[section_id]", section.id, new_admission.section_id.to_s.include?(section.id.to_s) ? true : false, required: true %>
					<% else %>
						<!-- On Initialization -->
						<%= radio_button_tag "section", section.id, false, required: true %>
					<% end %>
					<label for="student_section_id_<%= section.id %>"><%= section.name %></label>
				</div>
			</li>
		<% end %>
	</ul>
<% else %>
	<div class="alert alert-warning alert-empty">
		<strong>No Sections</strong>
	</div>
<% end %>
  

app/views/administrations/admissions/_enroll_form.html.erb
<div class="modal fade" id="admission_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Enroll New Admission</h4>
      </div>
      <div class="modal-body">
        <%= form_tag setup_admissions_path, method: :post do %>
        	<div class="form-group">
				    <label>*Batch</label>
				    <%= select_tag :batch, options_for_select(Batch.current_batches.map{|m| [m["name"], m["id"]]}), class: "form-control", prompt: "--Select Batch--", onchange: "gettingSections(this);" %>
				  </div>
			  	<div class="form-group">
            <label>*Sections</label>
            <div class="admission_sections">
				  	</div>
				  </div>
				  <div class="form-group">
				    <%= label_tag "Semester" %>
				    <%= select_tag :semester, options_for_select(Semester.current_semesters.map{|m| [m["name"], m["id"]]}), class: "form-control", prompt: "--Select Semester--" %>
				  </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" id="cancel-admission" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-success" id="new-admission">Proceed</button>
      </div>
    </div>
  </div>
</div>

app/views/administrations/admissions/_general_info.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="page-header">
      <h1>
      	Enroll new <small>Admission</small>
      </h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="panel-title">General Details</div>
      </div>
      <div class="panel-body">
      	<div class="form-group">
	        <div class="form-inputs">
	          <%= f.label :roll_number, "Roll Number:" %>
	          <%= f.input :roll_number, label: false, placeholder: "Roll Number" %>
	        </div>
        </div>
        <div class="form-group">
	        <div class="form-inputs">
	          <%= f.input :first_name, label: false, placeholder: "First Name", required: true %>
	        </div>
        </div>
        <div class="form-group">
	        <div class="form-inputs">
	          <%= f.input :last_name, label: false, placeholder: "Last Name" %>
	        </div>
        </div>
        <div class="form-group">
	        <div class="input-group date" id="form_student_dob">
	          <%= f.input :date_of_birth, label: false, placeholder: "Date of Birth", :as => :string, input_html: { id: "" } %>
	          <span class="input-group-addon">
	            <span class="fa fa-calendar"></span>
	          </span>
	        </div>
        </div>
        <div class="form-group">
	        <div class="form-inputs">
	          <%= f.input :gender, collection: ["Male", "Female"], as: :select, prompt: "--Select Gender--", label: false %>
	        </div>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="panel-title">Contact Details</div>
      </div>
      <div class="panel-body">
      	<div class="form-group">
	        <div class="form-inputs">
        		<%= f.input :address, label: false, placeholder: "Address" %>
      		</div>
    		</div>
      </div>
    </div>
  </div>
  <div class="col-md-6 col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="panel-title">Other Details</div>
      </div>
      <div class="panel-body">
      	<div class="form-group">
	        <div class="form-inputs">
	          <%= f.input :nationality, label: false, placeholder: "Nationality" %>
	        </div>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="panel-title">Academic Details</div>
      </div>
      <div class="panel-body">
      	<div class="form-group">
	        <div class="form-inputs">
	          <%= f.label :batch, "Batch:" %>
	          <%= f.association :batch, as: :select, collection: Batch.current_batches.map{|m| [m["name"], m["id"]]}, label: false, include_blank: "--Choose Batch--", :input_html => { onchange: "gettingSections(this, 'true');" } %>
	        </div>
        </div>
        <div class="form-group">
	        <div class="form-inputs">
	          <br/>
				  	<div class="form-group">
              <label>*Sections</label>
              <div class="admission_sections">
					  		<%= render "administrations/admissions/batches_sections", sections: resource.batch.sections, new_admission: resource %>
					  	</div>
					  </div>
	        </div>
        </div>
        <div class="form-group">
	        <div class="form-inputs">
	          <%= f.label :semester, "Semester:" %>
	          <%= f.association :semester, as: :select, label: false, include_blank: "--Choose Semester--" %>
	        </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/administrations/admissions/_guardian_relation.html.erb
<div class="row">
	<div class="col-md-6">
		<div class="page-header">
		  <h1>Guardians <small>Relation</small></h1>
		</div>
		<label>Enter Guardian Name:</label>
		<div class='form-group search_g_form'>
			<div class="input-group">
	      <input type="text" autocomplete="off" name="parent_name" id="query" placeholder="Parent Name" class="form-control" data-provide="typeahead"/>
	      <div class="input-group-addon query-loader"><i class="fa fa-bars"></i></div>
	    </div>
			<p id='parent_search_validator' class="hidden_name" style='color: rgb(128, 117, 117); display:none;'>	Please Enter Name</p>
			<br />
			<button class="btn btn-default" id="search_guardian" data-parent-id="">Search Guardian</button>
		</div>
	</div>
</div>

<div class="searched_guardians" style="display:none;"></div>
<div class="choose_guardians">
	<div class="alert alert-success" role="alert">Search Guardian with their Nic</div>
</div>

app/views/administrations/admissions/_list_parent.html.erb
<div class="row">
  <div class="col-md-offset-1 col-xs-12 col-sm-6 col-md-10">
    <div class="well" style="background: rgba(236, 236, 236, 0.1);">
      <div class="page-header">
        <h2><%= @parent.name %></h2>
      </div>
      <div class="row">
        <div class="col-xs-6 col-md-2">
          <a href="javascript: void(0)" class="thumbnail">
            <%= image_tag("default-avatar.png", class: "img-rounded") %>
          </a>
        </div>
        <div class="col-md-10">
          <div class="well">
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Phone #</th>
                    <th>Gender</th>
                    <th>Address</th>
                    <th>Occupation</th>
                    <th>Income</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td><%= @parent.id %></td>
                    <td><%= @parent.name %></td>
                    <td><%= @parent.phone %></td>
                    <td><%= @parent.gender %></td>
                    <td><%= @parent.home_address %></td>
                    <td><%= @parent.occupation %></td>
                    <td><%= @parent.monthly_income %></td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div id="searched_guardian_dependents">
            <%#= render "guardian_dependents", searched_guardian: @searched_guardian, :new_admission => @new_admission %>
          </div>
          <div class="alert alert-danger alert-dismissible" role="alert">
            <div id="relation">
              <ul class="list-inline">
                <li class="s_dependant" onclick="">
                  <%= link_to "Save Relation", "javascript: void(0)", :class => "btn btn-danger btn-lg" %>
                </li>
              </ul>
            </div>
          </div>    
        </div>
      </div>
    </div>
  </div>
</div>

app/views/administrations/admissions/_student_account.html.erb
<div class="page-header">
	<h1>Creating <small>Student Account</small></h1>
</div>

<div class="row">
	<div class="col-lg-offset-3 col-md-6 col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="panel-title">Student Account</div>
      </div>
      <div class="panel-body">
      	<div class="form-group">
          <div class="form-inputs">
            <%= f.label :email, "Email:" %>
            <%= f.input :email, label: false, placeholder: "Email", required: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="form-inputs">
            <%= f.label :username, "Username:" %>
            <%= f.input :username, label: false, placeholder: "Username", required: true %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/administrations/admissions/get_parent.js.erb
<% if @parent.present? %>
	console.log("<%= @parent %>")
	$(".choose_guardians").hide()
	$(".searched_guardians").hide().html("<%= escape_javascript(render 'shared/list_parent') %>").fadeIn(500)
<% else %>
	swal("Sorry", "There is no such Parent available", "error")
<% end %>