config/routes.rb
Rails.application.routes.draw do

  # Routes for Room Reservation
  get 'room_reservation/index'
  get "room_reservation/search_allocations" => "room_reservation#search_allocations"
  get "room_reservation/schedule_time_cell/:week_day/:time" => "room_reservation#schedule_time_cell", as: :schedule_a_time
  get "room_reservation/:batch_id/teacher_allocations" => "room_reservation#teacher_allocations", as: :teacher_allocations
  post "scheduling_room" => "room_reservation#book_room", as: :scheduling_room
  delete "dismiss_reserved_room" => "room_reservation#dissmiss_reserved_room", as: :dismiss_room

  # Routes for Dashboard
  get "/load_reserved_details" => "dashboard#load_reserved_details", as: :load_details
  get ":username/time_table" => "dashboard#time_table", as: :time_table
  

  # Routes for Students and Teachers
  constraints(Subdomain) do
    resources :profiles, :path => ":username", only: [:index] do
      collection do
        get "/settings" => "profiles#edit", as: :edit
        put "settings/security" => "profiles#security", as: :security
        put "settings/profile" => "profiles#update", as: :profile
      end
    end

    %w(student teacher).each do |resource|
      resource_name = resource.pluralize
      devise_for resource_name.to_sym, :skip => [:passwords, :registrations], controllers: { confirmations: "resources/confirmations", sessions: "resources/sessions" }
      devise_scope resource.to_sym do
        get "#{resource_name}/login" => "resources/sessions#new", as: "#{resource_name}_login".to_sym
        get "#{resource_name}/login_after_confirmation" => "resources/sessions#login_after_confirmation", as: "#{resource_name}_login_after_confirmation".to_sym
      end

      authenticated resource.to_sym do
        root 'dashboard#index', as: "#{resource}_authenticated_root".to_sym
      end
    end
  end

  # Routes for Admin
  constraints :subdomain => "admin" do 
    devise_for :admins, :skip => [:passwords, :registrations, :confirmations], controllers: { sessions: "resources/sessions" }
    devise_scope :admin do
      get "admin/login" => "resources/sessions#new", as: :admins_login
    end

    %w(student teacher).each do |resource|
      devise_for resource.pluralize.to_sym, :skip => [:passwords, :confirmations, :sessions], controllers: { registrations: "resources/registrations" }
      devise_scope resource.to_sym do
        if resource == "student"
          get "#{resource.pluralize}/admissions/:batch_name" => "resources/registrations#new", as: "new_#{resource}".to_sym
        else
          get "#{resource.pluralize}/new" => "resources/registrations#new", as: "new_#{resource}".to_sym
        end
      end
    end
    
    scope :module => 'administrations' do
      # Admin Settings
      resources :settings, :path => "admin/settings", only: [:index] do 
        collection do
          get "/account" => "settings#admin_account", as: :admin_account
          put "/" => "settings#update", as: :update_account
          get "/week_days" => "settings#week_days_and_timings", as: :set_week_days
          get "/current_batches" => "settings#current_batches", as: :current_batches
        end
      end

      resources :admissions, only: [:index] do
        collection do 
          post "/cancel_admission" => "admissions#cancel_admission", as: :cancel
          post "/setup_admission" => "admissions#setup_admission", as: :setup
          get "/autocomplete_guardians_search" => "admissions#autocomplete_guardians_search", as: :autocomplete_guardians
          get "/get_parent/:parent_id" => "admissions#get_parent"
        end
      end

      # Admin Students
      resources :students, path: "students", only: [:index] do
        get "/search" => "students#search", on: :collection, as: :search
      end

      # Admin Teachers
      resources :teachers, path: "teachers", only: [:index, :update] do
        get "/search" => "teachers#search", on: :collection, as: :search
      end

      resources :time_table, path: "time_table", only: [:index] do
        get "/generate" => "time_table#show", as: :generate, on: :collection
      end
    end

    authenticated :admin do
      root 'dashboard#index', as: :admin_authenticated_root
    end
  end

  namespace :institutes do
    resources :batches, except: [:show, :edit, :new] do
      put "/add_sections" => "batches#add_sections", as: :add_sections
    end

    get "/get_sections" => "base#get_sections", as: :get_sections

    resources :classrooms, except: [:edit]
    resources :courses do 
      get "get_course/:semester_name" => "courses#get_course_by_section", on: :collection
    end
    resources :course_allocations, only: [:index, :create, :update] do
      collection do
        post "allocate"
        get ":batch_id/get_allocations" => "course_allocations#get_allocations", as: :get_allocations
        delete ":batch_id/remove_allocations" => "course_allocations#remove_allocations", as: :remove_allocations
        get ":batch_id/courses_and_sections"=> "course_allocations#courses_and_sections", as: :courses_and_sections
        delete ":teacher_id/remove_teacher_allocations"=> "course_allocations#remove_teacher_allocations", as: :remove_teacher_allocations
        get "/notify_teacher_for_approval" => "course_allocations#notify_teacher_for_approval", as: :notify_teacher
      end
    end
  end

  resources :dashboard, only: [:index]

  get "/about_us" => "landings#about"
  root to: "landings#home"
end

app/controllers/administrations/admin_service.rb
class Administrations::AdminService
  def call
    admin = Admin.find_or_create_by!(email: Rails.application.secrets.admin_email) do |admin|
      admin.password = Rails.application.secrets.admin_password
      admin.password_confirmation = Rails.application.secrets.admin_password
      admin.is_admin = true
      admin.username = Rails.application.secrets.admin_username
      # admin.confirm!
    end
  end

  def setting_admin_account
  	admin_user = call
  	@admin_account = admin_user.build_account
  	subdoamin_name = admin_user.email.split("@").first
  	@admin_account.subdomain = subdoamin_name
  	@admin_account.save
  end

  # module_function :call, :setting_admin_account
end

app/controllers/administrations/admissions_controller.rb
module Administrations
	class AdmissionsController < ApplicationController
		before_action :get_new_admission_sections, only: [:new, :create]

		def setup_admission
	  	admission_params_hash = {
				:section => params[:section],
				:batch => params[:batch],
	      :semester => params[:semester]
	  	}
 	
	  	@admission = Student.build_admission(admission_params_hash)

	  	@batch_name = Batch.find(@admission.batch_id).batch_name if params[:batch].present?

	    respond_to do |format|
	    	if @admission.valid? == true
	        session[:admission] = @admission
	    		format.json { render :json => { status: :ok, redirect_url: new_student_path(@batch_name) }, status: :created }
	  		else
					format.json { render :json => { status: :error, errors: @admission.errors.full_messages.map { |msg| content_tag(:li, msg) }.join }, status: :created }
	  		end
	    end
	  end

		def cancel_admission
			session[:admission] = nil
			redirect_to students_path
			flash[:notice] = "Admission Cancelled"
		end

		def autocomplete_guardians_search
			@guardian_names = Parent.all.collect do |parent|  {
	        :id => parent.id,
	        :name => parent.name
	      }
	    end.to_json

			respond_to do |format|
				format.json { render :json => @guardian_names }
			end
		end

		def get_parent
			@parent = Parent.find(params[:parent_id]) if params[:parent_id]
			respond_to do |format|
				format.js
			end
		end

		private

		def get_new_admission_sections
			@admission_sections = Batch.find(session[:admission]["batch_id"]).sections
		end
	end
end

app/controllers/administrations/settings_controller.rb
module Administrations
	class	SettingsController < ApplicationController
		before_action :authenticate_admin!
		before_action -> { sidebar(true) }
		before_action -> { admin_settings_aside(true) }

		def admin_account
			@admin = current_admin
		end

		def week_days_and_timings
			@week_days = TimeSlot.week_days
			@normal_timings = TimeSlot.non_fridays
			@friday_timings = TimeSlot.fridays
		end

		def current_batches
			@current_batches = Batch.current_batches
		end

		def update
			@admin = current_admin
			if @admin.update_attributes(admin_params)
				sign_in :admin, @admin, :bypass => true
				redirect_to admin_account_settings_path, notice: "Account Updated"
			else
				render :admin_account
			end
		end

		private

		def admin_params
			params.require(:admin).permit(:email, :username, :password, :password_confirmation)
		end
	end
end

app/controllers/administrations/students_controller.rb
module Administrations
	class StudentsController < ApplicationController
		respond_to :js, :html
		add_breadcrumb "Students"
		
		def index
			@sections = Section.where(batch_id: Batch.current_batches.first["id"])
			@batches = Batch.current_batches

			respond_with :js, :html
		end


		def search
			@students, @batch = Search.students_search(params)
			respond_with :js
		end
	end
end

app/controllers/administrations/teachers_controller.rb
module Administrations
	class	TeachersController < ApplicationController
		add_breadcrumb "Teachers"
		
		def index
			@teachers = Teacher.present
		end

		def search
			@teachers = Search.teachers_search(params)
			render :index
		end

		def update
			@teacher = Teacher.find(params[:id])
			respond_to do |format|
				if @teacher.update_attributes(teacher_params)
					format.json { respond_with_bip(@teacher) }
				else
					format.json { respond_with_bip(@teacher) }
				end
			end
		end

		def teacher_params
			params.require(:teacher).permit(:full_name, :date_of_birth, :joining_date, :phone)
		end
	end
end

app/controllers/administrations/time_table_controller.rb
class Administrations::TimeTableController < ApplicationController
  include TimeTableSlots

  prepend_before_action :slots_data, only: [:show]
  add_breadcrumb "Time Table"

  def index
    @batches = Batch.current_batches
    @sections = @batches.first["sections"]
  end

  def show
    @reservations = TimeTable.generate(params)
    @params = params
    respond_to do |format|
      unless @reservations.blank?
        format.js {}
        format.html { render partial: 'administrations/time_table/generated_time_table' }
      else
        format.json { render json: { status: :empty, alert: TimeTable::NULL_RESERVATIONS } }
      end
    end
  end
end

app/controllers/time_table_controller.rb
class TimeTableController < ApplicationController
	prepend_before_action :time_table_slots, only: [:teacher_allocations]
	include AllocationsHelper
  respond_to :json

  def index
  end

  def search_allocations
  	allocations = $redis.get("teacher_allocations_#{current_resource}")

  	if allocations.blank?
  		@teacher_allocations = current_resource.under_approval_allocations #Only Under Approval

  		allocations = []
			@teacher_allocations.each do |allocation|

				sections = allocation.sections(allocation).order("name").collect {|m| m.try(:name) }

				allocations << {
					course: allocation.course.name,
					course_type: allocation.course.type_name,
					section: pluralize_sections(sections),
					batch: allocation.batch.name,
					semester: allocation.semester.try(:name),
					sent_date: "---"
				}
        
			end

			allocations = allocations.to_json
			$redis.set("teacher_allocations_#{current_resource}", allocations)
			$redis.expire("teacher_allocations_#{current_resource}", 2.minutes.to_i)
		end

		@allocs = JSON.load allocations
    
		respond_to do |format|
  		format.json { render json: { data: @allocs } }
		end
  end

  def teacher_allocations
    @batch_id = params[:batch_id]
  	@teacher_allocations = current_resource.under_approval_allocations(@batch_id)
  	respond_to do |format|
  		format.js {}
		end
  end

  def schedule_time_cell
  	@batch = Batch.find(params[:batch_id])

  	@timeslot = TimeSlot.find_by_week_day_and_start_time(params[:week_day], params[:time])
  	@count_allocations = $redis.get("count_teacher_allocations_#{@batch.id}")

  	if @count_allocations.blank?
  		@allocations = current_resource.course_allocations.under_approval.where(batch_id: @batch.id)

			pending_allocations = @allocations.pending_allocations
			logger.debug "------------#{pending_allocations.length}"
			@count_allocations = @allocations.length - pending_allocations.length

  		$redis.set("count_teacher_allocations_#{@batch.id}", @count_allocations.to_json)
      $redis.expire("count_teacher_allocations_#{@batch.id}", 30.seconds.to_i)
  	end

		@count_teacher_allocations = @count_allocations

    @teacher_allocations = current_resource.under_approval_allocations(@batch.id)

    @available_classrooms = @timeslot.available_classrooms

  	respond_to do |format|
  		format.js {}
		end
  end

  def book_room
    logger.debug "Params are :-> #{params}"

    @course_allocations = CourseAllocation.where(teacher_id: params[:teacher_id]).where(batch_id: params[:batch_id])

    result, course, section, room, slot = TimeTable.build_by_allocations @course_allocations, params

		logger.debug "Transaction: -> #{result}"

		@attributes = {
			course: course,
			section: section,
			room: room,
			batch: params[:batch_id],
			time_slot: slot
		}

		respond_to do |format|
			format.js {}
		end
	end

	def dissmiss_reserved_room
		logger.debug "Params are: -> #{params}"
		allocations = TimeTable.dismiss_reservations(params, current_resource)
		allocations.update_all("status = 0") if allocations.count > 1

		@reserved_allocation = allocations.where("time_tables.time_slot_id = ?", params[:slot_id])
		@reserved_allocation.destroy_all

		$redis.del("count_teacher_allocations_#{params[:batch_id]}")

		render :json => { status: :ok, current_domain: request.subdomain }
	end

  def time_table_slots
		@week_days = TimeSlot.week_days
		@non_fridays = TimeSlot.non_fridays
		@fridays = TimeSlot.fridays
  end
end

app/helpers/administrations/time_table_helper.rb
module Administrations::TimeTableHelper
  include RoomReservationHelper

  def rendering_time_table(params = {})
    render :layout => 'layouts/shared/time_table' do |time_table|
      html = ""
      if time_table.time_slot.booked_room_detail(params).each do |allocation|
        html << marked_cell(allocation, false, true)
      end.empty?
        html << "---"
      end
      html.html_safe
    end
  end

  def profile_time_popover_title(slot)
    return "Classes on #{slot.week_day}, #{slot.timings}"
  end

  def profile_time_popover_content(teacher, slot)
    render :partial => 'layouts/shared/teacher_dashboard_slot_detail', locals: { teacher: teacher, slot: slot }  
  end
end

app/views/administrations/time_table/_generated_time_table.html.erb
<div class="row">
  <div class="col-md-12">
    <table class="table table-bordered" id="time_table">
      <tr>
        <td align="center" rowspan="2">
          <strong>Fridays</strong>
          <div class="divider-cell"></div>
          <strong>Days</strong>
        </td>
        <% @fridays.each do |timing| %>
            <td align="center"><%= timing.timings %></td>
        <% end %>
      </tr>
      <tr>
        <% @non_fridays.each do |timing| %>
            <td align="center"><%= timing.timings %></td>
        <% end %>
      </tr>
      <tr class="period_days">
        <td align="center"><strong>Week Days</strong></td>
        <% (1..9).each do |period_days| %>
            <td align="center"><%= period_days %></td>
        <% end %>
      </tr>
      <% @week_days.each_with_index do |days, i| %>
          <tr>
            <td align="center"><strong><%= days.week_day %></strong></td>
            <% TimeSlot.for(days.week_day).each do |time_slot| %>
                <td align="center" class="loader-cell-<%= time_slot.id %>" data-time-slot-id="<%= time_slot.id %>">
                  <% if @reservations.for_time_slot(time_slot.id).each do |allocation| %>
                    <% options =
                           {
                               batch_id: allocation.course_allocation.batch_id,
                               course: allocation.course_allocation.course,
                               section: allocation.course_allocation.section,
                               room: allocation.classroom,
                               slot_id: time_slot.id,
                               course_name: allocation.course_allocation.course.detailed_name
                           }
                    %>

                    <%= marked_cell(options, false, true, allocation.course_allocation.teacher.full_name) %>
                  <% end.empty? %>
                    ---
                  <% end %>
                </td>
            <% end %>
          </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/administrations/time_table/_time_table_sections.html.erb
<li class="list-group-item text-center" data-section-id="<%= section["id"] %>">
  <div class="radio" style="margin-top:1px;">
    <%= radio_button_tag :section_id, section["id"], false, id: "section_#{section["id"]}" %>
    <label for="section_<%= section["id"] %>" style="padding-left:7px;"><strong>Section <%= section["name"] %></strong></label>
  </div>
</li>

app/views/administrations/time_table/index.html.erb
<div class="page-header">
  <h1>Generate Time Table</h1>
  <p class="lead">Select Batch to generate Time Table:</p>
  <ul class="list-inline allocations_current_batches">
    <% @batches.each do |current_batch| %>
        <li>
          <div class="radio" style="margin-top:1px;">
            <%= radio_button_tag :current_batch_id, current_batch['id'], false, checked: @batches.first == current_batch, id: "current_batch_#{current_batch['id']}_radio", onchange: "gettingSections(this);" %>
            <label for="current_batch_<%= current_batch['id'] %>_radio" style="padding-left:7px;"><strong><%= current_batch["name"] %></strong></label>
          </div>
        </li>
    <% end %>
  </ul>
  <div class="row">
    <div class="col-md-3">
      <blockquote class="blockquote-reverse">
        <div class="time_table_sections">
          <%= render partial: "time_table_sections", collection: @sections, :as => :section %>
        </div>
      </blockquote>
    </div>
    <div class="col-md-4 center-block">
      <h2>
        <%= button_tag "View Approved Results", class: "generate_btn btn-block btn btn-lg btn-default", id: "generate_time_table", data: { url: generate_time_table_index_path } %>
      </h2>
    </div>
  </div>
  <hr />
  <div id="admin_timetable" class="text-center">
  </div>
</div>